# Generated by Django 4.2.6 on 2023-11-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('blood_type', models.CharField(max_length=5)),
                ('allergies', models.TextField()),
                ('current_medications', models.TextField()),
                ('blood_pressure', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.TextField(default='M'),
        ),
        migrations.AddField(
            model_name='customer',
            name='medical_information_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='HealthRecord',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
